language: objective-c
before_install:
    - brew update
    - brew upgrade xctool
    - sudo easy_install cpp-coveralls
    - gem install bundler
    - bundle install
script: bundle exec rake ci
after_success: bundle exec rake coverage
